server:
  port: 80

spring:
  application:
    name: springcloud-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
  instance:
    instance-id: springcloud-consumer:${server.port}